### PR TITLE
[Ready] Dynamic Recipe Loading System

### PR DESCRIPTION
**Pull request by joazlazer**
## Changes
- Adds the new `<recipe>` tag which allows the specification of the `type` of recipe via an attribute and the target resulting item through a `<stack>` tag inside the sub-tag `<recipe.result>`
- Adds classes needed for custom recipe panels and the dynamic recipe loading system, which includes `RecipeProvider`, an extensible abstract class that allows for the loading of recipes from other mods' custom recipe systems
- Adds `RecipeProvider`s for existing vanilla recipe systems:
  - `FurnaceRecipeProvider`
  - `ShapelessRecipeProvider`
  - `ShapedRecipeProvider`

## Documentation
recipes
recipe_indices
recipe_keys

## **TODO**
- [x] Implement `FurnaceRecipeProvider`
- [x] Implement `ShapedRecipeProvider`
- [x] Implement `ShapelessRecipeProvider`
- [x] Verify `OreDictionary` support
- [x] Verify `Template` support
- [x] Descriptive javadocs
- [x] Update in-game documentation 
- [x] Implement `key` recipe attribute and overloads for `RecipeProvider.hasRecipe(...)` & `RecipeProvider.getRecipeComponents(...)` that accept a `ResourceLocation` instead of a target output `ItemStack`

### CODE REVIEW

**Comment by joazlazer** [comment]
The Recipe system should be ready to merge. While `OreDictionary` support hasn't been fully verified (since none of the recipes in vanilla are ore recipes), once this gets pushed, I can verify its support in my own personal development environment.

I have not implemented any of the more specialized vanilla `IRecipe` implementations such as firework or banner crafting, but I don't believe these are a very high priority. (although it can be done if need be. It might be as simple as adding an `if(recipe instanceof xxx)` to `CraftingRecipeProvider.reloadCaches()`, although I'm not sure and don't care to try right now).

P.S. @gigaherz Please make a branch for your `<span>` system so others can help / give feedback. Thanks!

**Comment by gigaherz** [comment]
Nice! I'll take a look as soon as I'm reasonably awake.

**Comment by Necr0** [comment]
Looks amazing. I was planning to do something similar but I'm still in the middle of a massive rework of my own mod. However, there is one thing I was wondering about. Don't all recipes in 1.12+ have a unique identifier in the form a resource location? I didn't really look into 1.12 recipes that much yet but they have to be registered using a registry event and all registry entries must have a resource location as a registry name. So couldn't we also use this to load a recipe? At least that's the way I was planning to implement dynamic recipe loading.
Could you also implement this if you have the time and motivation. I would do it myself but I have very little time recently which is why I am even struggling to update my own mod. Anyways both PRs look amazing, nicely done!

**Comment by joazlazer** [comment]
I'll take a look at it @Necr0, although I hadn't even thought of that. However, furnace recipes for example are not registered via `json` and I would venture to bet most custom recipe systems aren't either. I can do it, though, because it would probably be better (and much more consistent) than the recipe indices.

_Sent from my Samsung SM-N920I using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by joazlazer** [comment]
Ok, I added a registry key feature and added in-game documentation & javadoc for it. Ready to merge @gigaherz

**Comment by gigaherz** [comment]
Nice, I'll take a look in a bit.

**Pull request merged**
